fix compile failures on macos m1
```
error[E0425]: cannot find value `rootfs` in this scope
  --> src/start.rs:47:43
   |
47 |         let full_guest = format!("{}{}", &rootfs, guest_path);
   |                                           ^^^^^^ help: a local variable with a similar name exists: `_rootfs`

error[E0133]: call to unsafe function is unsafe and requires unsafe function or block
  --> src/start.rs:61:15
   |
61 |     let ret = bindings::krun_set_mapped_volumes(ctx, vols.as_ptr());
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
   |
   = note: consult the function's documentation for information on how to avoid undefined behavior

```

Signed-off-by: Davanum Srinivas <davanum@gmail.com>